### PR TITLE
2 fix weak security headers

### LINKED ISSUE #2: Fix weak security headers

### PR DESCRIPTION
**Pull request by JamieVangeysel**

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -75,29 +75,10 @@ function setupLogging(elasticConfig, loggingConfig, serviceName) {
...
-  })
-
-  fastify.addHook('onSend', (request, reply, payload, done) => {
-    reply.header('request-id', request.id)
-    done()
-  })
+  fastify.addHook('onRequest', require('./hooks/onRequest.hooks'))
+  fastify.addHook('onResponse', require('./hooks/onResponse.hook'))
+  fastify.addHook('preHandler', require('./hooks/preHandler.hook'))
+  fastify.addHook('onSend', require('./hooks/onSend.hook'))
```
Comment (OhSoooLucky) [inline index.js:82]: Unrelated to this PR

**Review by OhSoooLucky — APPROVED** [review]
